#!/bin/bash
# Runs the standard networking commands and writes README.md with output + explanation.
# Works on Ubuntu / WSL / Mac (some commands fall back if not installed).
# Usage: ./generate_readme.sh
cd "$(dirname "$0")"

# cap <title> <explanation> <command>
cap() {
  local title="$1" expl="$2" cmd="$3"
  local out
  out=$(eval "$cmd" 2>&1 | head -n 40)
  cat <<EOF

## $title

\`\`\`bash
$cmd
\`\`\`

\`\`\`text
$out
\`\`\`

**What I understood:** $expl

EOF
}

{
cat <<EOF
# Networking Fundamentals Homework

**Name:** Anushka Jain

All outputs below are from my machine, generated by [\`generate_readme.sh\`](./generate_readme.sh).

## Task 1
Practiced the commands from the devops-hero GitHub repo. Task 2 below shows each command, its output and what I learnt.

## Task 2: Networking commands
EOF

cap "hostname / hostname -I" \
"\`hostname\` prints the machine name. \`hostname -I\` prints all IP addresses assigned to this machine (on Mac use \`ipconfig getifaddr en0\`)." \
"hostname; hostname -I 2>/dev/null || ipconfig getifaddr en0"

cap "ip addr / ifconfig" \
"Shows every network interface (lo = loopback, eth0/ens/en0 = ethernet or wifi, docker0 = Docker bridge) with its MAC address, IPv4/IPv6 address and subnet mask. This is how I find my private IP." \
"ip addr 2>/dev/null || ifconfig"

cap "ip route / netstat -rn" \
"Prints the routing table. The \`default via X\` line is the gateway (my router) that traffic leaves through when the destination is not on my local network." \
"ip route 2>/dev/null || netstat -rn | head -n 15"

cap "ping" \
"Sends ICMP echo requests to check if a host is reachable and measures round trip time (latency) and packet loss. \`-c 4\` sends 4 packets." \
"ping -c 4 google.com"

cap "traceroute" \
"Shows every hop (router) a packet passes through to reach the destination and the latency at each hop. Useful to find where a connection slows down or breaks." \
"traceroute -m 15 google.com 2>/dev/null || tracepath -m 15 google.com"

cap "nslookup" \
"DNS lookup: converts a domain name into its IP address and shows which DNS server answered." \
"nslookup google.com"

cap "dig" \
"More detailed DNS query tool. The ANSWER SECTION shows the records (A record = IPv4). \`dig +short\` gives just the IP." \
"dig google.com +noall +answer; echo; dig +short google.com"

cap "curl" \
"Makes HTTP requests from the terminal. \`-I\` fetches only response headers, showing status code (200 OK), server and content type. Used to test APIs and web servers." \
"curl -sI https://www.google.com"

cap "wget" \
"Downloads files over HTTP/HTTPS. \`--spider\` just checks the URL exists without downloading." \
"wget --spider https://www.google.com 2>&1 || curl -s -o /dev/null -w 'HTTP status: %{http_code}\\n' https://www.google.com"

cap "netstat / ss (listening ports)" \
"Lists sockets. \`-t\` TCP, \`-u\` UDP, \`-l\` listening, \`-n\` numeric, \`-p\` process. Shows which ports are open on my machine and which program owns them." \
"if command -v ss >/dev/null; then ss -tulnp | head -n 20; else netstat -an | grep LISTEN | head -n 20; fi"

cap "arp" \
"Shows the ARP cache: mapping of IP addresses to MAC addresses of devices on my local network." \
"arp -a | head -n 10 || ip neigh"

cap "nc (netcat) port check" \
"Tests whether a specific port on a host is open. \`-z\` scans without sending data, \`-v\` verbose. Here checking port 443 (HTTPS) on google.com." \
"nc -zv google.com 443"

cap "nc port test on port 80" \
"Same check on port 80 (HTTP). If it says succeeded the port is reachable; -w 3 gives a 3 second timeout." \
"nc -zv -w 3 google.com 80"

cap "whois" \
"Shows domain registration info: registrar, creation date, name servers." \
"whois google.com 2>/dev/null | head -n 20 || echo 'whois not installed: sudo apt install whois'"

cat <<EOF

## Summary of what I learnt

- **IP address / subnet**: found with \`ip addr\`. Private IPs (10.x, 172.16-31.x, 192.168.x) are only reachable inside the LAN.
- **Gateway / routing**: \`ip route\` shows where packets go when leaving my network.
- **DNS**: \`nslookup\` and \`dig\` translate names to IPs. If DNS fails, \`ping 8.8.8.8\` works but \`ping google.com\` does not.
- **Connectivity**: \`ping\` for reachability, \`traceroute\` for the path, \`nc\`/\`telnet\` for a specific port.
- **Ports & sockets**: \`ss\`/\`netstat\` show what is listening on my machine. Common ports: 22 SSH, 80 HTTP, 443 HTTPS, 3306 MySQL.
- **HTTP tools**: \`curl\` and \`wget\` let me talk to web servers directly, which is how I will debug Docker containers and APIs later.
EOF
} > README.md

echo "README.md generated in networking/. Review it and push."
