#!/bin/bash
# Runs the full Git homework in a scratch repo and writes README.md with real output.
# Usage: ./practice.sh
cd "$(dirname "$0")"
OUT=/tmp/git-hw.txt; : > "$OUT"
run() { echo "\$ $*" >> "$OUT"; eval "$@" >> "$OUT" 2>&1; echo >> "$OUT"; }

rm -rf /tmp/git-practice && mkdir /tmp/git-practice && cd /tmp/git-practice
run 'git init -b main'
run 'git config user.name "Anushka Jain"; git config user.email "anushkaj460@gmail.com"'

echo "### TASK 1: git commit -m vs git commit -a -m" >> "$OUT"
run 'echo "first line" > file.txt'
run 'git add file.txt'
run 'git commit -m "commit 1: add file.txt"'
run 'echo "second line" >> file.txt'
run 'git status --short'
echo "# git commit -m WITHOUT staging -> nothing gets committed" >> "$OUT"
run 'git commit -m "trying commit without add"'
echo "# git commit -a -m -> automatically stages modified tracked files and commits" >> "$OUT"
run 'git commit -a -m "commit 2: modify file.txt using -a"'
run 'git log --oneline'
echo "# NOTE: -a only stages tracked files. New (untracked) files still need git add" >> "$OUT"
run 'echo new > untracked.txt'
run 'git commit -a -m "this will not include untracked.txt"'
run 'git status --short'
run 'git add untracked.txt && git commit -m "commit 3: add untracked.txt"'

echo "### TASK 2: git cherry-pick" >> "$OUT"
run 'echo "main change" >> file.txt && git commit -a -m "commit 4: main branch work"'
run 'git log --oneline'
run 'git checkout -b feature'
run 'echo "feature 1" > f1.txt && git add . && git commit -m "feature commit A: add f1.txt"'
run 'echo "feature 2" > f2.txt && git add . && git commit -m "feature commit B: add f2.txt"'
run 'echo "feature 3" > f3.txt && git add . && git commit -m "feature commit C: add f3.txt"'
run 'git log --oneline'
HASH=$(git log --oneline | grep "feature commit B" | cut -d" " -f1)
echo "# Picked commit B: $HASH" >> "$OUT"
run 'git checkout main'
run "git cherry-pick $HASH"
run 'git log --oneline'
run 'ls'
run 'git show --stat HEAD'
run 'git branch'

cd - >/dev/null
cat > README.md <<EOF2
# Git / GitHub Homework

**Name:** Anushka Jain

All output below generated by [\`practice.sh\`](./practice.sh).

## Task 1: git commit -m vs git commit -a -m

| | \`git commit -m "msg"\` | \`git commit -a -m "msg"\` |
|---|---|---|
| What it commits | Only what is already in the staging area (\`git add\`) | Automatically stages **all modified and deleted tracked files**, then commits |
| Untracked (new) files | Not included | Still not included, you must \`git add\` them |
| Typical use | When you want to pick exactly which changes go in | Quick commit of edits to existing files |

## Task 2: git cherry-pick

Cherry-pick copies **one specific commit** from another branch onto the current branch, without merging the whole branch. Steps done: 4 commits on \`main\`, new \`feature\` branch with 3 commits, picked commit B into \`main\`, verified with \`git log\` and \`ls\`.

## Full command log with output

\`\`\`text
$(cat "$OUT")
\`\`\`
EOF2
echo "README.md written in git-github/. Push it."
